name: Rust Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  # RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
        
  build_and_test:
    runs-on: ubuntu-latest
    # needs: [clippy_check]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
